gen-tfrecord:

	tf2
	http://download.tensorflow.org/models/object_detection/tf2/20200711/mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8.tar.gz
    mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8
	
	# 家中生成 一定要激活labelme 生成两个json
    conda activate labelme
	python 1labelme2coco.py images/train --output images/train.json
	python 1labelme2coco.py images/val --output images/val.json
	
	# 家中生成 一定要激活conda/env/tf290虚拟机 生成两个record文件
    conda activate tf290
	python 2create_coco_tf_record.py --logtostderr 
	--train_image_dir=images/train 
	--val_image_dir=images/val 
	--train_annotations_file=images/train.json 
	--val_annotations_file=images/val.json 
	--include_masks=True 
	--output_dir=./annotations
	
    # 生成 label_map.pbtxt
	python 3gen_label_map.py







dl-model:
	mkdir -p pre-trained-models; \
	model=mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8; \
	curl -O http://download.tensorflow.org/models/object_detection/tf2/20200711/$$model.tar.gz; \
	tar zxvf $$model.tar.gz; \
	mv -f $$model ./pre-trained-models/; \
	rm -rf $$model $$model.tar.gz;
train:
    ! python model_main_tf2.py --model_dir=models/mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8 --pipeline_config_path=models/mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8/pipeline.config
eval:
	python model_main_tf2.py 
    --pipeline_config_path=models/mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8/pipeline.config 
    --model_dir=models/mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8 
    --checkpoint_dir=models/mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8 
    --alsologtostderr
.PHONY: export
export:
	!python exporter_main_v2.py 
	--input_type image_tensor 
	--pipeline_config_path models/mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8/pipeline.config
	--trained_checkpoint_dir models/mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8
	--output_directory exported_models/my_model
serving:
	docker pull tensorflow/serving
	docker run -d --name serving_base tensorflow/serving
	# https://stackoverflow.com/a/45552938/14785930
	docker exec -it serving_base mkdir -p /models/test-mask/1
	docker cp exported-models/mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8/saved_model/. serving_base:/models/test-mask/1
	docker commit --change "ENV MODEL_NAME test-mask" serving_base test-mask
	docker rm -f serving_base
serving-test:
	python deployments/serving/client.py
flask:
	cp annotations/label_map.pbtxt deployments/flask
	cd deployments/flask && make build